### ISSUE TITLE
Cmdlet Naming convention

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/powershell-sdk#1]
Cmdlet generally uses a "prefix" to noun to differentiate from other modules.
For instance: `Get-ADUser` vs. `Get-AzureADUser`

Generally, use "singular" names for cmdlet. This "singular" cmdlet is also used to get a list.
For instance, `Get-ADUser` or `Get-AzureADUser` can return a single account (based on its guid/login) or a list of accounts, filtered or not. 

Verbs should follow the convention as documented by Microsoft: https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.3
For instance, `Test` can be used to test source health, etc.

 `Search-Post` do not reflect any noun and should not be used or perhaps not publicly available, and underneath a `Find-Indice`.
 I'd rather have `Find-Identity`, `Find-AccessProfile`, etc. than an unmeaningful, complex to use cmdlet.

**Comment by jordan-violet-sp** [comment]
This is a valid concern, and understand that it is the convention of Powershell. As of today, though, the automation used in generating our SDKs with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) doesn't allow for this to be implemented.
