### ISSUE TITLE
Setting a proxy is not working : bad type used

### ISSUE THREAD

**Issue by patrice-adp** [sailpoint-oss/powershell-sdk#12]
I tried to set a proxy using Set-Configuration -Proxy but wasn't working

The proxy was initalized using that : New-Object System.Net.WebProxy("proxy:port") but the configuration was failing raising an error that only System.Net.SystemWebProxy is supported (or System.Net.WebRequest+WebProxyWrapperOpaque but this one is not the one bothering me)

The problem is that the type of the proxy in reality is System.Net.WebProxy so it can't work. I wasn't able to generate proxy of type System.Net.SystemWebProxy from powershell

Can you fix it everywhere this check is done ?

**Comment by tyler-mairose-sp** [comment]
Hey @patrice-adp,

This was fixed with your PR https://github.com/sailpoint-oss/powershell-sdk/pull/34. Thank you for your contribution to the SDK!
