### ISSUE TITLE
Get-AccessToken is not using the proxy

### ISSUE THREAD

**Issue by patrice-adp** [sailpoint-oss/powershell-sdk#13]
When you configure a proxy because your server has no direct access to the internet, there's an issue as the Get-AccessToken method from Configuration.ps1 at the root of the project is not using it.

Due to that the access token can't be generated and the following rest calls fail with error : {"error":"JWT is required"}

Can you check why the proxy is not being used on that part and ensure it's used everywhere when it's set ?

**Comment by tyler-mairose-sp** [comment]
Hello @patrice-adp,

Thank you for adding this into the SDK! Due to spacing issues I created a PR https://github.com/sailpoint-oss/powershell-sdk/pull/36 off of your code to fix this issue.
