### ISSUE TITLE
False Positive Configuration Error 

### ISSUE THREAD

**Issue by Anneragh** [sailpoint-oss/powershell-sdk#15]
False positive error:  I am using the environmental variable configurations, not from config.yaml. 

I am using configuration from the below variables:
$env:SAIL_BASE_URL = "https://{tenant}-dev.api.identitynow.com"
$env:SAIL_CLIENT_ID = "{id}"
$env:SAIL_CLIENT_SECRET = "{secret}"

Which throws the below error:
**"Configuration file not found at C:\Users\{username}/.sailpoint/config.yaml. Please provide a configuration file or configure
using PowerShell environment variables. "** 

However, the API call responded with the expected payload.

**Comment by tyler-mairose-sp** [comment]
Hello @Anneragh,

Thank you for bringing this to our attention and helping to make our SDKs better!

This is fixed in https://github.com/sailpoint-oss/powershell-sdk/pull/17 and will be part of the next release.
