### ISSUE TITLE
Pagination example fails with invalid URL

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/powershell-sdk#2]
When I run the examples for search or paginated search, it fails with:
Cannot convert value "/oauth/token" to type "System.UriBuilder". Error: "Invalid URI: The hostname could not be parsed."

PSSailpoint\v3\src\PSSailpoint\Api\SearchApi.ps1 function Search-Post(), line 380

stepping through it with the debugger shows the configuration is being loaded but basically ignored, unless I'm missing some step.

**Comment by tyler-mairose-sp** [comment]
Hello @rob-buskens-sp,

First, I would like to confirm that you are using the latest version of the SDK. `1.0.2`

Looking at your error it seems like the baseurl is not getting set.

There are two ways to set your configuration. 

Through a configuration file located at $HOME/.sailpoint/config.yaml which I've included an example here. Where `example` is your tenant name.

```bash
activeenvironment: example # the key that identifies the currently active environment
authtype: pat # currently only pat and pipeline are supported if the ENV VAR SAIL_AUTH_TYPE is configured to "pipeline" it will override this value
customexporttemplatespath: "" # the path to the users custom export templates file if one is provided
customsearchtemplatespath: "" # the path to the users custom search templates file if one is provided
debug: false # the debug setting for the cli
environments: # the configured environments for the cli
  example:
    baseurl: https://example.api.identitynow.com
    pat:
      accesstoken: example-access-token
      clientid: example-client-id
      clientsecret: example-client-secret
      expiry: example-access-token-expiry
    tenanturl: https://example.identitynow.com
```

The other way is to set PowerShell environment variables. If environment variables are set, these will take precedent over the configuration file.

```powershell
$env:SAIL_BASE_URL=https://{org}.api.identitynow.com
$env:SAIL_CLIENT_ID={clientID}
$env:SAIL_CLIENT_SECRET={clientSecret}
```

**Comment by rob-buskens-sp** [comment]
Resolved through a number of steps
Updated to 1.0.2 of module (uninstall, reinstall)
Removed local github clone of repo (ensure the right code was executed)
Did some cleanup
Was still failing under vscode
Ran in terminal and it worked
Restarted vscode and it now works. Seems something was hanging on to an older (possibly modified) bit of library
