### ISSUE TITLE
Token in configuration gets re-used when switching tenants

### ISSUE THREAD

**Issue by bradgrutsch** [sailpoint-oss/powershell-sdk#28]
**Setup**: Powershell SDK with no config.yaml configured (i.e. we're just using environment variables)

**Steps to Reproduce:**
1. Run small sample script that sets the $env:SAIL_BASE_URL, $env:SAIL_CLIENT_ID, and $env:SAIL_CLIENT_SECRET for tenant 1 and then calls a cmdlet in the PSSailpoint module
2. Change $env:SAIL_BASE_URL, $env:SAIL_CLIENT_ID, and $env:SAIL_CLIENT_SECRET to valid values for tenant 2 and re-run the script

**Expected Results:** The script should run and return values for tenant 2

**Actual Results:** The script returns an error about the JWT token not being correct because it's using the same token retrieved in step 1 above (i.e. for tenant 1).  

If I run Get-DefaultConfiguration I can see that token is still set and TokenExpiration reflects the time from the tenant 1 token.  I have tried running Set-DefaultConfiguration and setting Token and TokenExpiration values to various versions of null but that doesn't seem to do anything.

**Comment by tyler-mairose-sp** [comment]
@bradgrutsch Thank you for brining this to our attention. This issue is fixed in https://github.com/sailpoint-oss/powershell-sdk/pull/33. If your config.yaml or environment variables change, the next call made will retrieve a token for the new environment.
