### ISSUE TITLE
Pagination function should write the output as soon as possible

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/powershell-sdk#3]
Currently, the `Invoke-Paginate` cmdlet wait for the pagination to end before returning the objects.
This increase memory consumption and slow down the process, especially with pipelines.
`Invoke-Paginate` should write to the output (cf. `write-output` for instance) as soon as possible.

**Comment by rob-buskens-sp** [comment]
The functionality to wait for all results is often very useful, and required for many use cases I've worked on. Yes it can take time and use memory. An example is you can't process the results unless you have ALL the input. The current implementation handles these nicely.

Being able to process results on the way would tremendous for other cases.

The Invoke-Paginate could take an argument of a function which would be passed the current of results. In this case it may make sense to not build up the total results to return. So there could be memory savings, and the results can be processed along the way.

I imagine this would block the next page, until result processing were done. If the function were invoked asynch then some mechanism to limit threading would be desirable... or you could end up having a lot of stuff happening in parallel and causing issues.

**Comment by yannick-beot-sp** [comment]
This is idiomatic to PowerShell.
For instance, with AD cmdlets, let's say you want for force the password change at next logon for a given OU:

```powershell
Get-ADUser -Filter *  -SearchBase "OU=Test,DC=corp,DC=com" | Set-ADUser -ChangePasswordAtLogon $true
```

You can also do:
```powershell
$users = Get-ADUser -Filter *  -SearchBase "OU=Test,DC=corp,DC=com"
$users | Set-ADUser -ChangePasswordAtLogon $true
```
or if you do not like pipes:
```powershell
$users = Get-ADUser -Filter *  -SearchBase "OU=Test,DC=corp,DC=com"
foreach($user in $users) {
  Set-ADUser -Identity $user -ChangePasswordAtLogon $true
}
```
The 2 last commands will retrieve all users before setting the userAccountControl flag.
The thing is that the first command will be _noticeably_ **faster**.

The same goes for exporting info to files for instance.

**Comment by yannick-beot-sp** [comment]
Here is an example:
```
function Get-Numbers {
    [CmdletBinding()]
    param ()
    

    
    process {
        for ($i = 0; $i -lt 10; $i++) {
            Write-Output $i
        }
    }
  
}
$a = Get-Numbers
<#
0
1
2
3
4
5
6
7
8
9
#>
$a = Get-Numbers | Select-Object -First 3
<#
0
1
2
#>
```

**Comment by tyler-mairose-sp** [comment]
Hey @yannick-beot-sp,

I've added this in https://github.com/sailpoint-oss/powershell-sdk/pull/80

Can you double check me to make sure this is what you're looking for and expecting?

**Comment by tyler-mairose-sp** [comment]
@yannick-beot-sp, I've merged in the code and it is working great. Thank you so much for this PR! I think many users will appreciate it.
