### ISSUE TITLE
Basic Get-Sources fails

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/powershell-sdk#30]
$sources = Get-Sources -Offset 0 -Limit 250

fails with:

ConvertFrom-Json: /Users/rob.buskens/.local/share/powershell/Modules/PSSailpoint/1.0.3/cc/src/PSSailpointCC/Private/CCApiClient.ps1:269:16
Line |
 269 |          return ConvertFrom-Json $Response
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. The key that was
     | attempted to be added to the existing key 'userauth.mergeColumns' was 'UserAuth.mergeColumns'.

Having inspected the result of the call, it looks like a valid JSON collection.

Rob

**Comment by tyler-mairose-sp** [comment]
Hey @rob-buskens-sp,

I updated the SDK to use the -AsHashTable switch when calling ConvertFrom-Json. This will allow both casings to be present within the PSObject.

It should be fixed with https://github.com/sailpoint-oss/powershell-sdk/commit/5df140c64e9dde6f6871643df67f7685f79baa99
