### ISSUE TITLE
CMDLET Collision: Get-AccessToken already exists in another PS module... (MSCloudLoginAssistant)

### ISSUE THREAD

**Issue by chadcarlton** [sailpoint-oss/powershell-sdk#43]
MSCloudLoginAssistant also has a cmdlet named "get-accesstoken".

https://github.com/microsoft/MSCloudLoginAssistant

Please advice on best path forward..

**Comment by tyler-mairose-sp** [comment]
Hey @chadcarlton,

I re-named our Get-AccessToken cmdlet to Get-IDNAccessToken in https://github.com/sailpoint-oss/powershell-sdk/commit/1177e86c8e4b835bddc1432b0632a707422ebb3f.

The change will be in the next release, or you can download the code from github and install it manually.

Thank you for submitting this issue!

**Comment by jordan-violet-sp** [comment]
This issue has been mentioned on **SailPoint Developer Community Forum**. There might be relevant details there:

https://developer.sailpoint.com/discuss/t/powershell-script-for-downloading-campaign-reports/20077/1
