### ISSUE TITLE
Install instructions reference PSYaml module. Is 'Powershell-YAML' ok instead?

### ISSUE THREAD

**Issue by chadcarlton** [sailpoint-oss/powershell-sdk#44]
`Install-Module -Name PSYaml -RequiredVersion 1.0.2`

The 'PSYaml' project looks like it has not been maintained lately : https://github.com/Phil-Factor/PSYaml

is it ok to use the 'powershell-yaml' project instead?  https://github.com/cloudbase/powershell-yaml

(I already had powershell-yaml installed and hit a CMDLET conflict when trying to install PSYaml module.

**Comment by tyler-mairose-sp** [comment]
Hey @chadcarlton,

The need for PSYaml has been removed, it supported an older version of configuration that we no longer need.

PSYaml has been removed in https://github.com/sailpoint-oss/powershell-sdk/pull/83 and will be gone in the next release.
