### ISSUE TITLE
Invoke-PaginateResults is breaking and not sending all the results back

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/powershell-sdk#7]
In PSSailpoint>1.0.2>Pagination.ps1>function invoke-PagnateSearch, looks like a bug.

<img width="688" alt="image" src="https://user-images.githubusercontent.com/105882429/224557909-11892537-6876-41fb-946a-89a5f27a169d.png">

if the $Result.length  is less than the $Increment it's breaking.
However there can be results. e.g. paging by 50, and there were 1 - 49 results.
it's throwing those away by breaking out of the while loop without adding the remaining items.

I added the last result to the total results before the break and it now returns all results

            if($Result.Length -lt $Increment) {
                $Results += $Result
                break
            }

            $Results += $Result
            $InitialOffset += $Increment;

**Comment by tyler-mairose-sp** [comment]
Hello @rob-buskens-sp, good catch! This is fixed by https://github.com/sailpoint-oss/powershell-sdk/pull/10 and will be included in the next release!
