### ISSUE TITLE
Remove or replace Install-Module inside the psm1 file

### ISSUE THREAD

**Issue by hakhundov** [sailpoint-oss/powershell-sdk#74]
Hi,

Would it be possible to remove (or replace with `Import-Module`) the `Install-Module -Name PSYaml -RequiredVersion 1.0.2` [in the PSSailpoint.psm1 file?](https://github.com/sailpoint-oss/powershell-sdk/blob/8ad67180854deb57f9523cee9abf0882ab50d300/PSSailpoint/PSSailpoint.psm1#L50)

It is causing a few issues, such as:
- Fails if module is installed w/o using PS gallery and no PSRepository is configured
- Runs w/o `-Scope` parameter and as such, requires elevated prompt
- Doesn't even try to load module into current session, so depends on implicit module loading (can be disabled in some environments)

**Comment by jordan-violet-sp** [comment]
This issue has been mentioned on **SailPoint Developer Community Forum**. There might be relevant details there:

https://developer.sailpoint.com/discuss/t/remove-or-replace-install-module-inside-the-psm1-file/37974/1

**Comment by BeejCyr** [comment]
Might this work?  It does not solve the scope issue, but should more gracefully handle the "no repository" concern and will load if the module was installed without the PS repository.
My 2 cents. 
```
$YamlMinVersion = [System.Version]::new("1.0.2")
If ((Get-Module -name PSYaml -ListAvailable | Sort-Object Version -Descending -Top 1).Version -lt $YamlMinVersion) {
    If (Get-PSRepository) {
        Install-Module -Name PSYaml -RequiredVersion $YamlMinVersion
    } else {
        Write-Error -Message "PSYaml not installed and no repositories are configured." 
    }
} else {
    Import-Module -Name PSYaml
}
```

**Comment by tyler-mairose-sp** [comment]
@BeejCyr, that code may work but this module PSYaml is only required for a piece of code that we ultimately need to remove. It supports pulling in baseurl, clientId, and clientSecret from the .sailpoint/config.yaml file. This configuration format is no longer recommended over environment or a local json config.

I am working on a PR now that will remove the need for PSYaml

**Comment by tyler-mairose-sp** [comment]
This is fixed with https://github.com/sailpoint-oss/powershell-sdk/pull/83 and will be present in the next release!
