### ISSUE TITLE
Error: JWT is Required

### ISSUE THREAD

**Issue by justinhaines** [sailpoint-oss/powershell-sdk#84]
I recently have been getting the following error on all of the SDK cmdlets that I run:

PS C:\Users\justin.haines> Get-AccessProfiles
Invoke-WebRequest: C:\Users\justin.haines\OneDrive - Optiv Security Inc\Documents\PowerShell\Modules\PSSailpoint\1.3.0\v3\src\PSSailpoint\Private\ApiClient.ps1:188
Line |
 188 |              $Response = Invoke-WebRequest -Uri $UriBuilder.Uri `
     |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  {   "error": "JWT is required" }

**Comment by tyler-mairose-sp** [comment]
Hey @justinhaines,

Has anything with your configuration changed? This leads me to think something is off with the baseurl, cliendId or clientSecret.

Would you mind sharing the output of the same `Get-AccessProfiles` but include the -Verbose switch. `Get-AccessProfiles -Verbose`

Make sure you exclude any sensitive data that is output.

**Comment by justinhaines** [comment]
I didn't realize I had to run sail idk init config --env <tenant> to set the environment. Thanks!

**Comment by justinhaines** [comment]
I didn't realize I had to run sail idk init config --env to set the environment. Thanks!
